### ISSUE TITLE
New cool project name

### ISSUE THREAD

**Issue by svnhmyr** [paulwellnerbou/sqlite-go-json#9] opened 2015-04-01 12:01 UTC
What about a very generic "Sql-To-Json"? (Btw Google serves +20000 hits for this name...)
Then you are free to migrate to http://www.rust-lang.org ;-P

**Comment by paulwellnerbou** [comment] 2015-04-02 15:07
But not free to server XML...

**Comment by paulwellnerbou** [comment] 2015-04-02 15:07
Duplicate of #5

**Closed as completed by paulwellnerbou** 2015-04-02 15:07 UTC
